### ISSUE TITLE
[android] fcm.registerForPushNotifications() error

### ISSUE THREAD

**Issue by Astrovic** [hansemannn/titanium-firebase-cloud-messaging#114]
Hi,
I'm testing the latest firebase.cloudmessaging 3.0.1, firebase.core 6.0.0 and Ti 9.1.0.GA, but I receive this error:

```java
[WARN]  FA: Failed to retrieve Firebase Instance Id
[DEBUG] TitaniumFirebaseCoreModule: (main) [36,87] FirebaseApp is already initialized.
[INFO]  Last data: [object Object]
[ERROR] TiExceptionHandler: (main) [9,96] /alloy/controllers/index.js:1007
[ERROR] TiExceptionHandler: fcm.registerForPushNotifications(),
[ERROR] TiExceptionHandler:     ^
[ERROR] TiExceptionHandler: Error: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
[ERROR] TiExceptionHandler:     at new Controller (/alloy/controllers/index.js:1007:5)
[ERROR] TiExceptionHandler:     at Object.exports.createController (/alloy.js:427:8)
[ERROR] TiExceptionHandler:     at /app.js:73:7
[ERROR] TiExceptionHandler:     at Module._runScript (ti:/module.js:587:9)
[ERROR] TiExceptionHandler:     at Module.load (ti:/module.js:106:7)
[ERROR] TiExceptionHandler:     at Module.loadJavascriptText (ti:/module.js:436:9)
[ERROR] TiExceptionHandler:     at Module.loadAsFile (ti:/module.js:488:15)
[ERROR] TiExceptionHandler:     at Module.loadAsFileOrDirectory (ti:/module.js:410:20)
[ERROR] TiExceptionHandler:     at Module.require (ti:/module.js:239:23)
[ERROR] TiExceptionHandler:     at Module.global.Module.require (<embedded>:4754:34)
[ERROR] TiExceptionHandler:
[ERROR] TiExceptionHandler:     com.google.android.gms.common.internal.Preconditions.checkNotEmpty(com.google.android.gms:play-services-basement@@17.3.0:8)
[ERROR] TiExceptionHandler:     com.google.firebase.iid.FirebaseInstanceId.zza(com.google.firebase:firebase-iid@@20.2.1:52)
[ERROR] TiExceptionHandler:     com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.1:2)
[ERROR] TiExceptionHandler:     com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.1:1)
[ERROR] TiExceptionHandler:     firebase.cloudmessaging.CloudMessagingModule.registerForPushNotifications(CloudMessagingModule.java:108)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Function.nativeInvoke(Native Method)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Function.callSync(V8Function.java:55)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Function.call(V8Function.java:41)
[ERROR] TiExceptionHandler:     ti.modules.titanium.TitaniumModule$Timer.run(TitaniumModule.java:156)
[ERROR] TiExceptionHandler:     android.os.Handler.handleCallback(Handler.java:900)
[INFO]  I/DecorView[]:  old windowMode:0 new windoMode:1
[INFO]  OverScrollerOptimization: start init SmartSlideOverScroller and get the overscroller config
[INFO]  OverScrollerOptimization: get the overscroller config
[ERROR] V8Exception: Exception occurred at /alloy/controllers/index.js:1007: Uncaught Error: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
```

This is my code:

**tiapp.xml**

```xml
<android xmlns:android="http://schemas.android.com/apk/res/android">
    <manifest android:versionCode="1" android:versionName="1.1" package="it.astrovicApps.aaaa" xmlns:android="http://schemas.android.com/apk/res/android">
      <uses-sdk android:targetSdkVersion="29"/>
      <application android:largeHeap="true">
        <activity android:configChanges="keyboardHidden|orientation" android:name="org.appcelerator.titanium.TiActivity" android:screenOrientation="portrait"/>
        
        <service android:name="it.astrovicApps.aaaa.gcm.RegistrationIntentService" android:exported="false"/>

        <receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true">
          <intent-filter>
            <action android:name="com.google.android.gms.measurement.UPLOAD"/>
          </intent-filter>
        </receiver>

        <service android:name="it.astrovicApps.aaaa.gcm.GcmIntentService" android:exported="false">
          <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
          </intent-filter>
        </service>

        <service android:name="it.astrovicApps.aaaa.gcm.GcmIntentService" android:exported="false">
          <intent-filter>
            <action android:name="com.google.android.c2dm.intent.SEND"/>
          </intent-filter>
        </service>

        <service android:name="it.astrovicApps.aaaa.gcm.GcmIDListenerService" android:exported="false">
          <intent-filter>
            <action android:name="com.google.android.gms.iid.InstanceID"/>
          </intent-filter>
        </service>

        <service android:name="com.google.firebase.components.ComponentDiscoveryService" >
          <meta-data android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
		android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>

        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713"/>
      </application>
    </manifest>
  </android>
  <modules>
    <module platform="android" version="6.0.0">firebase.core</module>
    <module platform="android" version="4.0.0">firebase.analytics</module>
    <module platform="android" version="3.0.1">firebase.cloudmessaging</module>
    <module platform="android">ti.playservices</module>
    <module>hyperloop</module>
  </modules>
```

**/app/platform/android/res/values/strings.xml**
```xml
<resources>
    <string name="google_app_id">1:5728...:android:def1ec97b187f1d5</string>
</resources>
```

**index.js**
```javascript
// Import core module
var FirebaseCore = require('firebase.core');

FirebaseCore.configure({
  APIKey: "000AIzaSyBatu3re.............",
  projectID: "api-project-5728...",
  storageBucket: "api-project-572873835784.appspot.com",
  applicationID: "1:5728...:android:def1ec97b187f1d5",
  GCMSenderID: '5728...',
  googleAppID: '1:5728...:android:def1ec97b187f1d5',
  file : "google-services-aaaa.json"
});

// Important: The cloud messaging module has to imported after (!) the configure()
// method of the core module is called
var fcm = require('firebase.cloudmessaging');

// Called when the Firebase token is registered or refreshed.
fcm.addEventListener('didRefreshRegistrationToken', function(e) {
    Ti.API.info('Token', e.fcmToken);
});

// Called when direct messages arrive. Note that these are different from push notifications.
fcm.addEventListener('didReceiveMessage', function(e) {
    Ti.API.info('Message', e.message);
});

// Android-only: For configuring custom sounds and importance for the generated system
// notifications when app is in the background
if (OS_ANDROID) {

    var channel = Ti.Android.NotificationManager.createNotificationChannel({
        id: 'default',
        name: 'Default channel',
        importance: Ti.Android.IMPORTANCE_DEFAULT,
        enableLights: true,
        enableVibration: true,
        showBadge: true
    });
    // if you use a custom id you have to set the same to the `channelId` in you php send script!

    fcm.notificationChannel = channel;

    // display last data:
    Ti.API.info("Last data: " + fcm.lastData);
} else {
	// iOS
	// Listen to the notification settings event
	Ti.App.iOS.addEventListener('usernotificationsettings', function eventUserNotificationSettings() {
	  // Remove the event again to prevent duplicate calls through the Firebase API
	  Ti.App.iOS.removeEventListener('usernotificationsettings', eventUserNotificationSettings);

	  // Register for push notifications
	  Ti.Network.registerForPushNotifications({
	    success: function () {Ti.API.info("registerForPushNotifications SUCCESS"); },
	    error: function () {Ti.API.info("registerForPushNotifications ERROR"); },
	    callback: function () { Ti.API.info("registerForPushNotifications CALLBACK");  } // Fired for all kind of notifications (foreground, background & closed)
	  });
	});

	// Register for the notification settings event
	Ti.App.iOS.registerUserNotificationSettings({
	  types: [
	    Ti.App.iOS.USER_NOTIFICATION_TYPE_ALERT,
	    Ti.App.iOS.USER_NOTIFICATION_TYPE_SOUND,
	    Ti.App.iOS.USER_NOTIFICATION_TYPE_BADGE
	  ]
	});
}

// Register the device with the FCM service.
fcm.registerForPushNotifications();

// Check if token is already available.
if (fcm.fcmToken) {
    Ti.API.info('FCM-Token', fcm.fcmToken);
} else {
    Ti.API.info('Token is empty. Waiting for the token callback ...');
}

// Subscribe to a topic.
fcm.subscribeToTopic('testTopic');
```

**Comment by m1ga** [comment]
`Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.`

remove the configure part and use the google json. That's easier

**Comment by Astrovic** [comment]
Ok, now I'm using

```javascript
FirebaseCore.configure({
    file : "google-services.json"
  });
```

but still the same error. Project ID is correct, I have been using this app for a few years now, just updated firebase modules an Ti SDK

**Comment by m1ga** [comment]
remove that line. A google-service.json will be read automatically with ti sdk 9.x if it is inside the plaform/android folder

**Comment by Astrovic** [comment]
Even using just `FirebaseCore.configure()` the problem persists.
I am using ti.playservices 17.1.1
With SDK 9.0.3 and earlier firebase versions it worked fine

**Comment by m1ga** [comment]
you can even remove `FirebaseCore.configure()` (I have to update the readme)
Strange. I'm using the latest version with 9.1.0. You could test https://github.com/appcelerator-modules/ti.playservices/releases/tag/v17.3.0 but shouldn't make a difference. It is strange that is complaining about the project-id when you use a newer sdk. strings.xml can also be empty now.

**Comment by Astrovic** [comment]
I've tried playservices 17.3.0, and removing `Firebase.configure()`, but still the same error... it's really very strange, I can't figure out what the problem could be

**Comment by hansemannn** [comment]
For questions, please use TiSlack for user-based errors. This is only for bugs related to the module errors.

**Comment by Astrovic** [comment]
It may be useful for someone to know that the error is due to the current latest version of ti.cloudpush (7.1.0). Using an older version, the module works correctly.
