### ISSUE TITLE
Android: Exception on receiving of push notification when internet is turned back on and app is in foreground

### ISSUE THREAD

**Issue by sachuisaac** [hansemannn/titanium-firebase-cloud-messaging#15]
**Scenario:**
The internet is turned off and a push notification is triggered from the server. The App is in foreground and the internet is turned on, push notification (data message) is received as the log says

```
FirebaseMsgService: Message Notification Body: Dear Sachu, Your request is granted.
```
then the following exception is displayed

```
[ERROR] :  TiApplication: (pool-10-thread-1) [890,1561171] Sending event: exception on thread: pool-10-thread-1 msg:java.lang.NullPointerException: Attempt to invoke virtual method 'void firebase.cloudmessaging.CloudMessagingModule.onMessageReceived(java.util.HashMap)' on a null object reference; Titanium 7.1.0,2018/03/14 13:40,undefined
[ERROR] :  TiApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'void firebase.cloudmessaging.CloudMessagingModule.onMessageReceived(java.util.HashMap)' on a null object reference
[ERROR] :  TiApplication: 	at firebase.cloudmessaging.TiFirebaseMessagingService.onMessageReceived(TiFirebaseMessagingService.java:51)
[ERROR] :  TiApplication: 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.firebase.iid.zzc.run(Unknown Source)
[ERROR] :  TiApplication: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
[ERROR] :  TiApplication: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
[ERROR] :  TiApplication: 	at java.lang.Thread.run(Thread.java:818)

[ERROR] :  AndroidRuntime: FATAL EXCEPTION: pool-10-thread-1
[ERROR] :  AndroidRuntime: Process: com.me.ex, PID: 1890
[ERROR] :  AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void firebase.cloudmessaging.CloudMessagingModule.onMessageReceived(java.util.HashMap)' on a null object reference
[ERROR] :  AndroidRuntime: 	at firebase.cloudmessaging.TiFirebaseMessagingService.onMessageReceived(TiFirebaseMessagingService.java:51)
[ERROR] :  AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
[ERROR] :  AndroidRuntime: 	at com.google.firebase.iid.zzc.run(Unknown Source)
[ERROR] :  AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
[ERROR] :  AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
[ERROR] :  AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```

I'm using the `titanium-firebase-cloud-messaging` version `android-1.0.2` and `titanium sdk` version `7.1.0`

Could you please let me know how to handle this?

**Comment by m1ga** [comment]
@sachuisaac can you please try this test version:
https://migaweb.de/firebase.cloudmessaging-android-1.0.3_test.zip
I'll added a null-check around that method.

**Comment by sachuisaac** [comment]
@m1ga The test version with null check doesn't cause the exception anymore, hence not crashing the app. Thank you for the response. Hoping to see the same on the main repository.

The scenario arised when the firebase core was not configured and fcm not initialized the second time I built the app. First time, after successful configuration and initialized, the fcm token was saved to our server and second time, the configuration and initialization was commented out (testing phase) in the next rebuild, hence the exception.

**Comment by hansemannn** [comment]
Thanks for the insight @sachuisaac! @m1ga Can you prepare the new version?

**Comment by m1ga** [comment]
Bugfix merged
