### ISSUE TITLE
Android: crash if the module is not yet initialized but onTokenRefresh event is called

### ISSUE THREAD

**Issue by gaspardle** [hansemannn/titanium-firebase-cloud-messaging#29]
Crash on this line: https://github.com/hansemannn/titanium-firebase-cloud-messaging/blob/master/android/src/firebase/cloudmessaging/CloudMessagingModule.java#L142

```
Process: com.communauto.reservauto, PID: 24871
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.appcelerator.kroll.KrollObject.hasListeners(java.lang.String)' on a null object reference
	at org.appcelerator.kroll.KrollProxy.hasListeners(KrollProxy.java:999)
	at firebase.cloudmessaging.CloudMessagingModule.onTokenRefresh(CloudMessagingModule.java:111)
	at firebase.cloudmessaging.TiFirebaseInstanceIDService.onTokenRefresh(TiFirebaseInstanceIDService.java:18)
	at com.google.firebase.iid.FirebaseInstanceIdService.zza(Unknown Source:71)
	at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent(Unknown Source:158)
	at com.google.firebase.iid.zzc.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by m1ga** [comment]
https://github.com/hansemannn/titanium-firebase-cloud-messaging/pull/30
