### ISSUE TITLE
Android: Warning I am seeing when receiving a notification 

### ISSUE THREAD

**Issue by jwogan5** [hansemannn/titanium-firebase-cloud-messaging#32]
I am running the latest 1.3.1 Android Module and the latest Appc SDK 7.4.1.  When I receive a push notifications I get the following error although everything still works.

[WARN]  FirebaseMessaging: Error while parsing timestamp in GCM event

[WARN]  FirebaseMessaging: java.lang.NumberFormatException: s == null
[WARN]  FirebaseMessaging:      at java.lang.Integer.parseInt(Integer.java:570)
[WARN]  FirebaseMessaging:      at java.lang.Integer.valueOf(Integer.java:794)
[WARN]  FirebaseMessaging:      at com.google.firebase.messaging.zzd.zzb(Unknown Source:60)
[WARN]  FirebaseMessaging:      at com.google.firebase.messaging.zzd.zzi(Unknown Source:2)
[WARN]  FirebaseMessaging:      at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source:277)
[WARN]  FirebaseMessaging:      at com.google.firebase.iid.zzg.run(Unknown Source:26)
[WARN]  FirebaseMessaging:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
[WARN]  FirebaseMessaging:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
[WARN]  FirebaseMessaging:      at java.lang.Thread.run(Thread.java:764)

**Comment by m1ga** [comment]
I think thats not a bug of the module but of the push you are sending. Make sure you set a `timestamp`.

**Comment by jwogan5** [comment]
@m1ga 

So doing some research on google it seems this is an issue with com.google.firebase:firebase-messaging.  An FCM packet does not contain a timestamp node.  People are saying to fix this issue you have to raise the version of this class to 17.3.0.   I'm not sure that will work for us as our play services are locked at 11.4.0 but I will try to just increase the version and see if the build passes.

**Comment by jwogan5** [comment]
The build failed :( so looks like the core module and all other modules would need to be raised for this fix to work.

**Comment by m1ga** [comment]
if you do that you need to raise the playstore module too and the core and so on. But that shouldn't be needed. I'm using the module without any problems.

But the fcm version should be raised soon, just takes some more work.

**Comment by antonioduran** [comment]
Hello @jwogan5 . I was reviewing very carefully the logcat, and I could noticed what you are saying... 
It is not crashing the app, but yep it is there... 

```
02-26 21:57:58.262 27082-27141/? W/FirebaseMessaging: Error while parsing timestamp in GCM event
                                                      java.lang.NumberFormatException: s == null
                                                          at java.lang.Integer.parseInt(Integer.java:570)
                                                          at java.lang.Integer.valueOf(Integer.java:794)
                                                          at com.google.firebase.messaging.zzd.zzb(Unknown Source:60)
                                                          at com.google.firebase.messaging.zzd.zzg(Unknown Source:26)
                                                          at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source:160)
                                                          at com.google.firebase.iid.zzg.run(Unknown Source:26)
                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                          at java.lang.Thread.run(Thread.java:784)
```
