### ISSUE TITLE
No static method zzb

### ISSUE THREAD

**Issue by yagitoshiro** [hansemannn/titanium-firebase-cloud-messaging#50]
App crashes on boot. By wrong combination of libraries?

Titanium SDK 7.5.0.GA

ti.playservices 11.8.0
firebase.core 3.0.2
firebase.cloudmessaging 1.4.0

Error message:
```
FATAL EXCEPTION: main
    Process: my.test.app, PID: 15149
    java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbo; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbo' appears in /data/app/jp.ibaraki.namegata.city.namegatakosodate-yycIKM5Ekuefpm0Fb9gTWA==/base.apk:classes2.dex)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7107)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6594)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6498)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by m1ga** [comment]
Please check: https://github.com/appcelerator-modules/ti.playservices/releases
11.8.0 is a prerelease. If you use the latest release (11.0.40) you should be fine

**Comment by yagitoshiro** [comment]
@m1ga thanks!
